# Generated by Django 2.0.7 on 2018-08-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('memberid', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('birth', models.DateTimeField()),
                ('phone', models.CharField(max_length=11)),
                ('gender', models.CharField(max_length=1)),
                ('tier', models.CharField(max_length=10)),
                ('TS_CREATED', models.DateTimeField()),
                ('TS_UPDATED', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='StockCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.TextField()),
                ('total_score', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
    ]
