# Generated by Django 2.0.7 on 2018-08-02 02:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_stockcard_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockcard',
            old_name='total_score',
            new_name='bigs_score',
        ),
        migrations.RenameField(
            model_name='stockcard',
            old_name='information',
            new_name='theme',
        ),
        migrations.AddField(
            model_name='stockcard',
            name='code',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
